FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app
COPY package.json package-lock.json turbo.json tsconfig.json ./


# Copy app and package directories
COPY apps ./apps
COPY packages ./packages

# Install dependencies
RUN npm install

# Run Prisma to generate database client
RUN npm run db:generate

# Build the specific app (user-app)
RUN npm run build-user-app

# Start the user-app
CMD ["npm", "run", "start-user-app"]